title: 'Computational Working Group'
description: "University of Chicago"
url: "UC-CWG.github.io"

header_pages:
  - index.md
  - about.md

style: hacker

footer: 'Questions? Contact Rochelle Terman: rterman@uchicago.edu'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
