title: 'Computational Working Group'
description: "University of Chicago"
url: "UC-CWG.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: hacker

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
